### ISSUE TITLE
Yarn Package?

### ISSUE THREAD

**Issue by kirichkov** [kktsvetkov/heiho#6]
It would be great to be able  to add this via Yarn.

**Comment by kktsvetkov** [comment]
Added package.json in b09a30e but I still need to publish it

**Comment by kktsvetkov** [comment]
https://www.npmjs.com/package/heiho

**Comment by kktsvetkov** [comment]
https://github.com/kktsvetkov/heiho/packages/414104

**Comment by kktsvetkov** [comment]
https://www.npmjs.com/package/@kktsvetkov/heiho

**Comment by kktsvetkov** [comment]
https://yarnpkg.com/package/@kktsvetkov/heiho
